server:
  port: 9000
spring:
  profiles:
    active: dev

  datasource:
    url: 139.224.72.89:3306/pay
    username: root
    password: 123456

  rabbitmq:
    host: 139.224.72.89
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        output-to-router:
          destionation: pay-router
      rabbit:
        bindings:
          output-to-router.producer:
            routingKeyExpression: '''router'''




